- hosts: "vps"
  vars:
    destination_dir: "/opt/tomcat/webapps/vh_safranlices/"
    source_repo: "https://github.com/remipassmoilesel/safran-des-lices"

  tasks:
  - name: "Push changes"
    raw: "cd {{ playbook_dir }} && git push origin master"
    delegate_to: localhost

  - name: "Update set-env file"
    copy:
      src: "./setenv-prod.sh"
      dest: "/opt/tomcat/bin/setenv-safran-lices.sh"

  - name: "Enable and start mysql"
    systemd:
      name: "mysql"
      enabled: "yes"
      state: "started"

  - name: "Enable and start postfix"
    systemd:
      name: "postfix"
      enabled: "yes"
      state: "started"

  - name: "Clone and update git project"
    git:
      repo: "{{ source_repo }}"
      dest: "/opt/safran-des-lices"

  - name: "Update application dependencies"
    bower:
      path: "/opt/safran-des-lices/src/main/resources/static"
      production: "yes"

  - name: "Package application"
    raw: "source /opt/tomcat/bin/setenv-safran-lices.sh && cd /opt/safran-des-lices && mvn package -DskipTests=true"

  - name: "Ensure destination directory exists"
    file:
      state: "directory"
      path: "{{ destination_dir }}"

  - name: "Deploy application"
    copy:
      remote_src: "yes"
      src: "/opt/safran-des-lices/target/safran-des-lices-0.0.1-SNAPSHOT.war"
      dest: "{{ destination_dir }}/ROOT.war"

  - name: "Enable and restart tomcat"
    systemd:
      name: "tomcat"
      enabled: "yes"
      state: "restarted"