- hosts: "vps"
  vars:
    project_root: "{{ playbook_dir }}/.."
    destination_dir: "/opt/tomcat/webapps/vh_safranlices/"
    static_root: "{{ project_root }}/src/main/resources/static"

  tasks:

  - name: "Update frontend dependencies"
    bower:
      path: "{{ static_root }}"
      production: "yes"
    delegate_to: localhost

  - name: "Package application"
    shell: "cd {{ project_root }} && mvn package -DskipTests=true"
    delegate_to: localhost

  - name: "Update set-env file"
    copy:
      src: "./setenv-prod.sh"
      dest: "/opt/tomcat/bin/setenv-safran-lices.sh"

  - name: "Enable and start mysql"
    systemd:
      name: "mysql"
      enabled: "yes"
      state: "started"

  - name: "Enable and start postfix"
    systemd:
      name: "postfix"
      enabled: "yes"
      state: "started"

  - name: "Delete old application directory"
    file:
      state: "absent"
      path: "{{ destination_dir }}"
    ignore_errors: "yes"

  - name: "Ensure destination directory exists"
    file:
      state: "directory"
      path: "{{ destination_dir }}"
      owner: "tomcat"

  - name: "Deploy application"
    copy:
      src: "{{ project_root }}/target/safran-des-lices-0.0.1-SNAPSHOT.war"
      dest: "{{ destination_dir }}/ROOT.war"
      owner: "tomcat"

  - name: "Enable and restart tomcat"
    systemd:
      name: "tomcat"
      enabled: "yes"
      state: "started"